### ISSUE TITLE
 Limitations for Docker Swarm on multiple Rasberry PIs?

### ISSUE THREAD

**Issue by Mikerr1111** [alexellis/docker-arm#21]
Hi, I was just wondering the limitations of Docker Swarm when it comes to connecting multiple Raspberry Pi's. I saw in the demo that you had 7 hooked up together. So if I was to hook up 10-12 Pi's would I run into any problems? Also, keep up the great work! 👍

**Comment by alexellis** [comment]
Hi @Mikerr1111, I've got larger than this before. I think 10-12 would be absolutely fine. You may want to set some of them as "master" nodes so that this task is balanced out in the cluster too.

Kubernetes doesn't scale as well on the RPi2/3 as it is quite intensive on the CPU. Swarm is lighter-weight and should go quite large.
